version: '3'

services:
    php:
        container_name: php-nginx
        image: webdevops/php-nginx-dev:8.2
        volumes:
            - ./:/app
            - ~/.ssh:/home/application/.ssh
        working_dir: /app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            WEB_DOCUMENT_INDEX: index.php
            PHP_MAX_EXECUTION_TIME: 3600
            PHP_DISPLAY_ERRORS: 1
            COMPOSER_MEMORY_LIMIT: -1
            DOMAIN_NAME: ${DOMAIN_NAME}
            VIRTUAL_HOST: ${DOMAIN_NAME}
            APPLICATION_UID: shell id -u
            APPLICATION_GID: shell id -g
            PHP_DEBUGGER: xdebug
            XDEBUG_REMOTE_AUTOSTART: 1
            COMPOSER_VERSION: 2
        ports:
            - "80:80"
        depends_on:
            - database
            - nodejs
        networks:
            - appnet

    database:
        container_name: db
        image: postgres:16
        ports:
            - '5432:5432'
        restart: always
        volumes:
            - ./docker/data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - appnet

    nodejs:
        container_name: node-js
        image: node:14-alpine
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
        working_dir: /app
        networks:
            - appnet

networks:
    appnet:
        driver: "bridge"

